Repository Wincewind/ohtu-s23-miniprojekti, pull requests merged in 2023-11, with the labels that each got.

#3 Set up ReactJS for frontend
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.js
  frontend/src/index.js
Labels: frontend

#6 Handle form submit, connect to frontend to backend, build frontend
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.js
  frontend/src/components/AddReferenceForm.js
  src/app.py
  src/build/asset-manifest.json
  src/build/index.html
  src/build/robots.txt
  src/build/static/js/main.96ccf699.js
  src/build/static/js/main.96ccf699.js.LICENSE.txt
  src/build/static/js/main.96ccf699.js.map
  src/routes.py
Labels: backend, frontend

#17 Install Material UI, add table for all references
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/ReferenceList.js
  src/build/asset-manifest.json
  src/build/index.html
  src/build/static/js/main.c120ddd9.js
  src/build/static/js/main.c120ddd9.js.LICENSE.txt
  src/build/static/js/main.c120ddd9.js.map
  src/build/static/js/main.f5f37162.js
  src/build/static/js/main.f5f37162.js.map
Labels: frontend

#20 Add get_all_references method
  src/dataprocessing.py
  src/entities/reference.py
  src/routes.py
  src/services/reference_services.py
Labels: backend, database

#21 Postgre service test
  .coveragerc
  .env.test
  .github/workflows/main.yml
  poetry.lock
  pyproject.toml
  pytest.ini
  run_robot_tests.sh
  src/dataprocessing.py
  src/entities/reference.py
  src/services/__init__.py
  src/services/reference_services.py
  src/tests/entities/test_reference.py
  src/tests/resource.robot
  src/tests/services/test_reference_services.py
  src/tests/test-schema.sql
  src/tests/test_add_reference.robot
  src/tests/test_dataprocessing.py
Labels: enhancement, backend, database

#25 Create retro.md and add acceptance criteria
  README.md
  retro.md
Labels: documentation

#30 Update retro.md
  retro.md
Labels: documentation
